### ISSUE TITLE
Matplotlib causes error on import when you first install

### ISSUE THREAD

**Issue by michael-denyer** [Cloufield/gwaslab#2]
When you install with maplotlib version 3.6 or greater it errors with the following:

"AttributeError: module 'matplotlib.cbook' has no attribute '_make_class_factory'"

Installing maplotlib < 3.6 after gwaslab is installed resolves this problem

**Comment by Cloufield** [comment]
Hi,  Michael

Thanks for the feedback. I tried to replicate this error but the installation worked well on my device with maplotlib v3.6. (Actually I am currently using the maplotlib v3.6 for gwaslab develpment)

Based on the error message itself, the reason might be `mpl_toolkit being a different version than the matplotlib base` according to https://github.com/matplotlib/matplotlib/issues/22656

Can you update the matplotlib to the latest version and see if gwaslab works?

**Comment by michael-denyer** [comment]
Hello,
It's a strange error but seems to be fixed if I install an earlier version of matplotlib than 3.6.2 after gwaslab is installed. If you can't replicate it then it must be something peculiar about my databricks ubuntu environment set up that is causing the issue.
Thanks for looking into it.
